import streamlit as st
import random

movies = {
    "O Exorcista": ["Conta a história de uma jovem possuída por um demônio.", 
                    "Dirigido por William Friedkin.", 
                    "Baseado em um romance de William Peter Blatty."],
    "Psicose": ["A famosa cena do chuveiro é um marco no cinema de terror.", 
                "Dirigido por Alfred Hitchcock.", 
                "Personagem icônico chamado Norman Bates."],
    "O Iluminado": ["Baseado em um livro de Stephen King.", 
                    "Jack Nicholson estrela como um zelador enlouquecido.", 
                    "Dirigido por Stanley Kubrick."],
    "Halloween - A Noite do Terror": ["Apresenta Michael Myers como vilão.", 
                                      "Dirigido por John Carpenter.", 
                                      "História se passa durante a noite de Halloween."],
    "A Hora do Pesadelo": ["Freddy Krueger ataca suas vítimas nos sonhos.", 
                           "Dirigido por Wes Craven.", 
                           "Filme tornou Robert Englund um ícone do terror."],
    "O Chamado": ["História gira em torno de uma fita de vídeo amaldiçoada.", 
                  "Protagonista tem sete dias para escapar da maldição.", 
                  "Adaptação de um filme japonês original."],
    "It - A Coisa": ["Baseado em uma obra de Stephen King.", 
                     "O vilão é um palhaço chamado Pennywise.", 
                     "Os protagonistas são um grupo de crianças conhecidos como 'O Clube dos Otários'."],
    "Hereditário": ["Filme que explora segredos sombrios de uma família.", 
                    "Dirigido por Ari Aster.", 
                    "Toni Collette tem uma atuação memorável."],
    "O Massacre da Serra Elétrica": ["Inspirado em uma história real.", 
                                     "Vilão é conhecido como Leatherface.", 
                                     "Filme é um marco no terror slasher."],
    "Atividade Paranormal": ["Filme de terror em estilo found footage.", 
                             "Foca em eventos sobrenaturais dentro de uma casa.", 
                             "Iniciou uma franquia de sucesso."],
    "Corra!": ["Filme aborda racismo com elementos de terror psicológico.", 
               "Dirigido por Jordan Peele.", 
               "Protagonista visita a família de sua namorada."],
    "A Bruxa de Blair": ["Um dos filmes mais famosos em estilo found footage.", 
                         "Grupo de jovens se perde em uma floresta assombrada.", 
                         "Lançado em 1999 e revolucionou o gênero."],
    "Invocação do Mal": ["Baseado nos casos reais dos investigadores Ed e Lorraine Warren.", 
                         "Dirigido por James Wan.", 
                         "História se passa em uma casa assombrada na década de 1970."],
    "Annabelle": ["Filme sobre uma boneca amaldiçoada.", 
                  "Parte do universo de 'Invocação do Mal'.", 
                  "História mistura possessão e forças demoníacas."],
    "O Babadook": ["História de uma mãe e seu filho enfrentando um monstro de um livro infantil.", 
                   "Dirigido por Jennifer Kent.", 
                   "Recebeu aclamação por sua metáfora sobre luto e trauma."],
    "Sexta-Feira 13": ["Jason Voorhees se tornou um ícone do terror.", 
                       "A maioria dos filmes se passa em Crystal Lake.", 
                       "O primeiro filme tem um twist sobre o assassino."],
    "Alien - O Oitavo Passageiro": ["Horror de ficção científica dirigido por Ridley Scott.", 
                                    "Protagonista é a oficial Ripley, interpretada por Sigourney Weaver.", 
                                    "A criatura alienígena tem um design marcante de H.R. Giger."],
    "Nosferatu": ["Um dos primeiros filmes de vampiro já feitos.", 
                  "Dirigido por F.W. Murnau em 1922.", 
                  "Baseado vagamente no romance 'Drácula' de Bram Stoker."],
    "Drácula de Bram Stoker": ["Adaptação do romance clássico de Bram Stoker.", 
                               "Gary Oldman interpreta o vampiro lendário.", 
                               "Dirigido por Francis Ford Coppola."],
    "A Bruxa": ["Se passa na Nova Inglaterra do século XVII.", 
                "Dirigido por Robert Eggers.", 
                "Explora a paranoia e o sobrenatural."],
    "Midsommar: O Mal Não Espera a Noite": ["Terror psicológico que se passa durante o dia.", 
                                           "Dirigido por Ari Aster.", 
                                           "Grupo de amigos participa de um festival sueco estranho."],
    "Suspiria": ["Obra-prima do terror italiano dirigida por Dario Argento.", 
                 "História envolve uma academia de dança com segredos macabros.", 
                 "Destaca-se pelo uso de cores vibrantes e trilha sonora marcante."],
    "A Entidade": ["Envolve uma série de filmes caseiros perturbadores.", 
                   "Estrelado por Ethan Hawke como um escritor investigando crimes.", 
                   "Apresenta um ser demoníaco chamado Bughuul."],
    "Carrie, a Estranha": ["Baseado em um livro de Stephen King.", 
                           "História de uma adolescente com poderes telecinéticos.", 
                           "Famosa cena do baile e do balde de sangue."],
        "O Homem Invisível": ["Versão moderna de um clássico de terror.", 
                          "Protagonista sofre com um ex-parceiro abusivo que se torna invisível.", 
                          "Dirigido por Leigh Whannell."],
    "A Casa de Cera": ["Grupo de amigos é perseguido em uma cidade sinistra.", 
                       "Os vilões transformam pessoas em figuras de cera.", 
                       "Tem Paris Hilton em seu elenco."],
    "Jogos Mortais": ["Apresenta armadilhas elaboradas e mortais para 'testar' as vítimas.", 
                      "O vilão é chamado Jigsaw.", 
                      "Dirigido por James Wan."],
    "Coraline e o Mundo Secreto": ["Filme de animação com elementos de terror.", 
                                   "Baseado na obra de Neil Gaiman.", 
                                   "Protagonista descobre uma versão paralela de sua vida."],
    "O Hospedeiro": ["Filme sul-coreano que mistura terror com crítica social.", 
                     "Monstro aquático emerge de um rio contaminado.", 
                     "Dirigido por Bong Joon-ho."],
    "Terror em Silent Hill": ["Baseado em um famoso jogo de videogame.", 
                              "Personagens ficam presos em uma cidade deserta e assombrada.", 
                              "Conhecido por seus visuais perturbadores."],
    "Boneco do Mal": ["Babá é contratada para cuidar de um boneco que é tratado como uma criança.", 
                      "Filme explora os limites entre a realidade e o sobrenatural.", 
                      "Tem uma reviravolta no final."],
    "A Morte do Demônio (Evil Dead)": ["Grupo de amigos encontra um livro maligno em uma cabana.", 
                                       "Filme tem cenas icônicas de gore.", 
                                       "Dirigido por Sam Raimi."],
    "REC": ["Filmado no estilo found footage.", 
            "História se passa em um prédio infestado por um vírus mortal.", 
            "Origem espanhola e altamente aclamado."],
    "Babadook": ["Um livro misterioso ameaça uma mãe e seu filho.", 
                 "Monstro se manifesta através do luto.", 
                 "Atmosfera psicológica e densa."],
    "Doce Vingança": ["Mulher busca vingança após sofrer um ataque brutal.", 
                      "Parte do gênero 'revenge horror'.", 
                      "Explora temas de brutalidade e justiça."],
    "A Profecia": ["História de um garoto que é a reencarnação do Anticristo.", 
                   "Filme cheio de símbolos religiosos.", 
                   "Teve várias sequências e remakes."],
    "A Autópsia": ["Dois legistas tentam resolver um caso misterioso envolvendo um cadáver.", 
                   "Terror claustrofóbico e psicológico.", 
                   "Dirigido por André Øvredal."],
    "O Ritual": ["Padre cético é enviado para Roma para estudar exorcismo.", 
                 "Baseado em eventos reais.", 
                 "Estrelado por Anthony Hopkins."],
    "O Albergue": ["Grupo de turistas cai em uma armadilha mortal durante viagem à Europa.", 
                   "Dirigido por Eli Roth.", 
                   "Parte do gênero 'terror extremo'."],
    "Casa de Usher": ["Baseado na obra de Edgar Allan Poe.", 
                      "História sobre uma mansão amaldiçoada e seus moradores.", 
                      "Atmosfera gótica e sinistra."],
    "O Sacrifício do Cervo Sagrado": ["Suspense psicológico com elementos de terror.", 
                                      "Estrelado por Colin Farrell e Nicole Kidman.", 
                                      "Baseado em uma tragédia grega."],
    "A Vila": ["Comunidade isolada vive com medo de criaturas na floresta.", 
               "Dirigido por M. Night Shyamalan.", 
               "Conhecido por sua reviravolta no final."],
    "O Anticristo": ["Explora temas de luto, dor e terror psicológico.", 
                     "Dirigido por Lars von Trier.", 
                     "Filme perturbador com cenas intensas."],
    "Hush - A Morte Ouve": ["Protagonista surda luta contra um assassino mascarado em sua casa isolada.", 
                            "Suspense tenso e claustrofóbico.", 
                            "Dirigido por Mike Flanagan."],
    "O Mistério de Candyman": ["Lenda urbana envolve um espírito vingativo.", 
                               "Personagem pode ser invocado ao dizer seu nome cinco vezes.", 
                               "Filme mistura terror e crítica social."],
    "A Morte Te Dá Parabéns": ["Uma jovem revive o mesmo dia repetidamente, terminando com sua morte.", 
                               "Terror com elementos cômicos e de ficção científica.", 
                               "Estrelado por Jessica Rothe."],
    "A Entidade 2": ["Continuação da história envolvendo o demônio Bughuul.", 
                     "Foco em uma nova família sendo perseguida.", 
                     "Dirigido por Ciarán Foy."],
    "Pânico": ["Revitalizou o gênero de terror nos anos 90.", 
               "Assassino usa uma máscara de 'fantasma' e liga para as vítimas.", 
               "Dirigido por Wes Craven."],
    "Arraste-me para o Inferno": ["Filme de terror sobrenatural com toques de humor negro.", 
                                  "Uma maldição é lançada sobre a protagonista após negar um pedido de empréstimo.", 
                                  "Dirigido por Sam Raimi."],
    "Cemitério Maldito": ["Baseado no livro de Stephen King.", 
                          "História de um cemitério que traz os mortos de volta à vida.", 
                          "Explora o luto e suas consequências."],
    "O Homem nas Trevas": ["Grupo de jovens tenta roubar a casa de um homem cego.", 
                           "Terror com forte suspense e reviravoltas.", 
                           "Dirigido por Fede Álvarez."],
    "A Múmia": ["História de uma antiga múmia que retorna para aterrorizar os vivos.", 
                "Versões clássicas incluem o monstro da Universal.", 
                "Explora maldições egípcias."],
    "Sombras da Noite": ["Baseado em uma série clássica de terror e drama.", 
                         "Personagem principal é um vampiro que acorda no século XX.", 
                         "Tim Burton dirige esta versão."],
    "O Culto": ["Grupo de amigos retorna a um culto misterioso que deixaram no passado.", 
                "Dirigido por Justin Benson e Aaron Moorhead.", 
                "Explora temas de tempo e realidade."],
    "Corrente do Mal": ["Maldição passa de uma pessoa para outra através de contato íntimo.", 
                        "Filme de terror psicológico com forte atmosfera.", 
                        "Dirigido por David Robert Mitchell."],
    "Hellraiser": ["Apresenta criaturas de outra dimensão chamadas Cenobitas.", 
                   "O vilão icônico é conhecido como Pinhead.", 
                   "Baseado na obra de Clive Barker."],
    "A Casa das Sombras": ["Protagonista se muda para uma casa com segredos sombrios.", 
                           "Mistura de terror psicológico e drama.", 
                           "Estrelado por Ruth Wilson."],
    "O Olho que Tudo Vê": ["Mulher que recebe transplante de córnea começa a ver espíritos.", 
                           "Baseado em um filme de terror asiático.", 
                           "Explora visões perturbadoras e sobrenaturais."],
    "A Casa Amaldiçoada": ["Grupo de pessoas é chamado para investigar fenômenos sobrenaturais em uma mansão.", 
                           "Clássico do terror psicológico.", 
                           "Dirigido por Robert Wise."],
    "Fenômenos Paranormais": ["Equipe de um reality show de terror entra em um hospital psiquiátrico assombrado.", 
                              "Filme em estilo found footage.", 
                              "Mistura ficção com elementos de documentário."],
    "Sobrenatural": ["História de uma família tentando salvar seu filho de uma dimensão maligna.", 
                     "Dirigido por James Wan.", 
                     "Apresenta o conceito de viagem astral."],
    "Boneca Assassina (Child's Play)": ["Filme de terror que apresenta um boneco chamado Chucky.", 
                                        "Boneco é possuído pelo espírito de um assassino.", 
                                        "Iniciou uma franquia de sucesso."],
    "O Exorcismo de Emily Rose": ["Baseado em um caso real de exorcismo.", 
                                  "Combina elementos de tribunal com horror.", 
                                  "Protagonista é uma jovem que acredita estar possuída."],
    "O Segredo da Cabana": ["Grupo de amigos em uma cabana se depara com forças sobrenaturais.", 
                            "Mistura clichês de terror com uma reviravolta surpreendente.", 
                            "Dirigido por Drew Goddard."],
    "O Predador": ["Monstro alienígena caça humanos por esporte.", 
                   "Tem elementos de horror e ficção científica.", 
                   "Protagonizado por Arnold Schwarzenegger no original."],
    "O Lobisomem": ["História clássica de um homem amaldiçoado que se transforma em lobisomem.", 
                    "Filme já teve várias versões, incluindo clássicos da Universal.", 
                    "Explora temas de maldição e identidade."],
    "Veronica": ["Filme espanhol baseado em um caso real de atividade sobrenatural.", 
                 "Grupo de adolescentes faz uma sessão espírita e invoca algo perigoso.", 
                 "Dirigido por Paco Plaza."],
    "O Enigma de Outro Mundo": ["Filme de ficção científica e horror sobre um ser que imita formas de vida.", 
                                "Ambientado em uma estação na Antártida.", 
                                "Dirigido por John Carpenter."],
    "O Mistério de Lillian": ["Menina com habilidades psíquicas lida com forças obscuras.", 
                              "Explora terrores psicológicos e sobrenaturais.", 
                              "Dirigido por Robert Eggers."],
    "Silêncio dos Inocentes": ["Thriller psicológico com forte componente de terror.", 
                               "História de um serial killer e um canibal.", 
                               "Estrelado por Anthony Hopkins como Hannibal Lecter."],
    "Herdeiro da Escuridão": ["Família descobre que seu filho é o anticristo.", 
                              "Temas de possessão e ocultismo.", 
                              "Mistura terror com drama familiar."],
    "Os Outros": ["Mulher e seus filhos vivem em uma casa com regras rígidas devido à luz.", 
                  "Mistério e terror psicológico com um grande twist.", 
                  "Estrelado por Nicole Kidman."],
    "Pânico na Floresta": ["Grupo de jovens se perde em uma floresta habitada por canibais.", 
                           "Explora o horror de sobrevivência.", 
                           "Parte do gênero slasher."],
    "O Vingador Tóxico": ["Horror trash com muito humor e violência exagerada.", 
                          "Filme de baixo orçamento que virou cult.", 
                          "Explora vingança e mutações."],
    "Mar Negro": ["Equipe de resgate enfrenta horrores em um navio fantasma.", 
                  "Combina elementos de terror psicológico com sobrenatural.", 
                  "Explora segredos sombrios do mar."],
    "O Poço": ["Filme de terror e ficção com elementos sociais.", 
               "História se passa em uma prisão vertical onde comida é escassa.", 
               "Explora desigualdade e sobrevivência."],
    "Campo do Medo": ["Grupo de pessoas fica preso em um campo de grama alta com entidades sobrenaturais.", 
                      "Baseado em uma história de Stephen King e Joe Hill.", 
                      "Dirigido por Vincenzo Natali."],

        "Caçadores de Trolls": ["Filme de terror norueguês em estilo mockumentary.", 
                            "Equipe de filmagem segue um caçador de trolls.", 
                            "Mistura mitologia com horror e humor."],
    "O Orfanato": ["Mulher retorna ao orfanato onde cresceu para reabrir o lugar.", 
                   "Eventos sobrenaturais começam a acontecer com seu filho.", 
                   "Produzido por Guillermo del Toro."],
    "O Segredo da Floresta": ["Amigos se perdem em uma floresta japonesa assombrada.", 
                              "Inspirado na verdadeira Floresta Aokigahara.", 
                              "Explora temas de luto e escuridão interna."],
    "Slender Man: Pesadelo Sem Rosto": ["Baseado na lenda urbana do Slender Man.", 
                                        "Grupo de amigas tenta desvendar o desaparecimento de uma delas.", 
                                        "Explora terror psicológico."],
    "A Maldição de Hill House": ["História de uma família assombrada por eventos traumáticos em uma mansão.", 
                                 "Baseado no livro de Shirley Jackson.", 
                                 "Dirigido por Mike Flanagan."],
    "Livrai-nos do Mal": ["Policial investiga casos com possíveis possessões demoníacas.", 
                          "Baseado em eventos reais.", 
                          "Mistura terror sobrenatural e policial."],
    "Anticristo": ["Casal tenta superar a morte do filho isolado em uma cabana na floresta.", 
                   "Dirigido por Lars von Trier.", 
                   "Explora temas de dor, culpa e horror psicológico."],
    "Do Inferno": ["História de Jack, o Estripador, em Londres vitoriana.", 
                   "Estrelado por Johnny Depp como um detetive.", 
                   "Baseado na graphic novel de Alan Moore."],
    "Mãe!": ["Suspense psicológico com elementos de terror.", 
             "Protagonista lida com eventos perturbadores em sua casa.", 
             "Dirigido por Darren Aronofsky."],
    "Creepshow": ["Antologia de contos de terror.", 
                  "Escrito por Stephen King e dirigido por George A. Romero.", 
                  "Homenagem aos quadrinhos de terror dos anos 50."],
    "Lobisomem Americano em Londres": ["Clássico do terror e comédia.", 
                                       "Dois amigos são atacados por uma criatura na Inglaterra.", 
                                       "Efeitos práticos lendários."],
    "Quando um Estranho Chama": ["Babá começa a receber ligações perturbadoras.", 
                                 "Clássico suspense e terror de perseguição.", 
                                 "Baseado em uma lenda urbana."],
    "A Maldição de Chucky": ["Chucky retorna para aterrorizar uma nova família.", 
                             "Continuação da franquia do Boneco Assassino.", 
                             "Mistura elementos clássicos com uma nova abordagem."],
    "Sobrenatural: A Origem": ["Prequel do universo Sobrenatural.", 
                               "Explora a origem dos eventos sobrenaturais que afligem a médium Elise.", 
                               "Dirigido por Leigh Whannell."],
    "Os Estranhos": ["Casal é aterrorizado por mascarados em sua casa isolada.", 
                     "Inspirado por eventos reais.", 
                     "Conhecido por sua atmosfera de puro medo."],
    "O Bar Luva Dourada": ["Baseado em uma história real de um serial killer alemão.", 
                           "Terror psicológico com atmosfera brutal e sombria.", 
                           "Retrata o submundo de Hamburgo nos anos 70."],
    "Terrifier": ["Assassino chamado Art the Clown persegue suas vítimas.", 
                  "Terror slasher com cenas de gore explícito.", 
                  "Cultuado por fãs do gênero."],
    "Nós": ["Família é aterrorizada por suas próprias cópias malignas.", 
            "Dirigido por Jordan Peele.", 
            "Explora temas de identidade e sociedade."],
    "A Chave Mestra": ["Mulher aceita cuidar de um idoso em uma casa com segredos ocultos.", 
                       "Terror baseado em vodu e rituais antigos.", 
                       "Protagonizada por Kate Hudson."],
    "O Grito": ["Maldição mortal é transmitida de vítima para vítima.", 
                "Baseado no filme japonês 'Ju-On'.", 
                "Explora o terror sobrenatural japonês."],
    "O Despertar dos Mortos": ["Terror de zumbis em um shopping center.", 
                               "Clássico de George A. Romero.", 
                               "Comentário social através do gênero de zumbis."],
    "The Witch in the Window": ["Pai e filho reformam uma casa assombrada.", 
                                "Mistura de drama familiar e terror psicológico.", 
                                "Atmosfera intensa e crescente."],
    "Os Olhos da Cidade são Meus": ["Filme de terror giallo italiano.", 
                                    "História de assassinatos em série e pistas bizarras.", 
                                    "Dirigido por Dario Argento."],
    "O Ritual do Medo": ["Culto secreto realiza rituais para perpetuar seus segredos.", 
                         "Mistura elementos sobrenaturais com horror psicológico.", 
                         "Explora as consequências do fanatismo."],
    "Alta Tensão": ["Amiga tenta proteger sua amiga e escapar de um assassino brutal.", 
                    "Terror francês com reviravoltas intensas.", 
                    "Explora temas de violência extrema."],
    "Casa do Medo": ["História de uma casa com uma entidade que possui os moradores.", 
                     "Mistura terror sobrenatural e psicológico.", 
                     "Filme de terror tailandês altamente elogiado."],
    "O Portão": ["Crianças acidentalmente abrem um portal para demônios no quintal.", 
                 "Terror dos anos 80 com toques de fantasia.", 
                 "Explora medos infantis e sobrenaturais."],
        "A Hora do Pesadelo": ["Freddy Krueger ataca suas vítimas nos sonhos.", 
                           "Criado por Wes Craven, tornou-se um ícone do terror.", 
                           "Mistura horror com temas psicológicos."],
    "O Exterminador do Futuro": ["Embora seja mais conhecido como ficção científica, o filme tem elementos de terror.", 
                                 "A luta entre humanos e máquinas é permeada por uma atmosfera de pavor.", 
                                 "Estrela Arnold Schwarzenegger como o temido ciborgue."],
    "A Noite dos Mortos Vivos": ["Filme de terror clássico que introduziu a ideia dos zumbis modernos.", 
                                 "Um dos maiores filmes de terror de todos os tempos.", 
                                 "Dirigido por George A. Romero."],
    "Evil Dead 2": ["Mistura de comédia e terror, com cenas sangrentas e grotescas.", 
                    "Continuação do filme original, com mais exagero e humor.", 
                    "Dirigido por Sam Raimi."],
    "Hellbound: Hellraiser II": ["Continuação de 'Hellraiser', explorando mais a mitologia dos Cenobitas.", 
                                 "O filme expande o universo do primeiro e traz mais criaturas de outro mundo.", 
                                 "Cultuado por fãs do gênero de terror."],
    "O Cemitério": ["Filme baseado no livro de Stephen King, sobre um cemitério que traz os mortos de volta à vida.", 
                    "O filme mistura terror psicológico e sobrenatural.", 
                    "Explora as consequências de mexer com a morte."],
    "Pesadelo Final – A Morte de Freddy": ["Último filme da saga Freddy Krueger nos anos 80.", 
                                           "Desfecho da luta contra o assassino dos sonhos.", 
                                           "Mistura terror psicológico com elementos surreais."],
    "Sexta-feira 13 - Parte 3": ["Jason Voorhees se torna um ícone do terror nesta terceira parte.", 
                                  "A ação se passa em um acampamento isolado, com muito sangue e gore.", 
                                  "O filme popularizou a máscara de hóquei do assassino."],
    "O Massacre da Serra Elétrica 2": ["Continuação do filme de 1974, com mais humor e exagero.", 
                                       "Filme que mistura terror com sátira e gore.", 
                                       "Terror psicológico misturado com o estilo de slasher."],
    "Vingança do Demônio": ["Filme de terror baseado em possessão demoníaca e eventos sobrenaturais.", 
                            "História cheia de suspense psicológico.", 
                            "Atraente para os fãs do terror gótico."],
    "A Coisa (It)": ["Baseado no livro de Stephen King, sobre um ser sobrenatural que assume a forma dos maiores medos das crianças.", 
                     "A versão de 1990 é uma minissérie que mistura terror e elementos psicológicos.", 
                     "O palhaço Pennywise se tornou um ícone do medo."],
    "A Morte Pede Carona": ["Filme de terror psicológico que mistura suspense com slasher.", 
                            "Sobre um motorista psicótico que dá carona a jovens inocentes.", 
                            "Direção de Robert Harmon."],
    "O Ataque dos Zumbis": ["Filme de zumbis clássico da década de 80.", 
                            "Gore exagerado e muito sangue.", 
                            "Parte da onda de filmes de terror de zumbis nos anos 80."],
    "A Noite das Bruxas": ["Comédia de terror, mas com elementos sombrios e góticos.", 
                           "Sobre um adolescente que descobre a verdade sobre a origem das bruxas.", 
                           "Filme com forte apelo nostálgico."],
    "A Maldição de Demônio": ["Filme de terror gótico que envolve rituais de magia negra e um mal antigo.", 
                              "Atmosfera sombria e cheia de mistério.", 
                              "Baseado em um conto de terror clássico."],
    "A Mão que Cria": ["Suspense psicológico de terror sobre uma pessoa que começa a perder o controle sobre seu corpo.", 
                       "Explora a loucura e o terror psicológico.", 
                       "Com muitos elementos sobrenaturais."],
    "Loucura no Campus": ["Filme de terror e comédia que mistura slasher e mistério.", 
                          "Ambientado em uma universidade com segredos sombrios.", 
                          "Mistura de sátira e horror."],
    "O Enigma de Outro Mundo (The Thing)": ["Clássico de John Carpenter que mistura terror e ficção científica.", 
                                            "Seres alienígenas tomam a forma de outros e espalham terror em uma estação isolada.", 
                                            "A tensão psicológica é um dos maiores elementos do filme."],
    "Os Garotos Perdidos": ["Mistura de vampiros e adolescência com um toque de comédia.", 
                            "Ambientado na Califórnia, tem se tornado um clássico cult.", 
                            "Estrela Kiefer Sutherland e Jason Patric."],
    "A Hora da Zona Morta": ["Baseado em um livro de Stephen King, o filme segue um homem que descobre ter habilidades psíquicas.", 
                             "Mistura terror com suspense psicológico e temas de moralidade.", 
                             "Direção de David Cronenberg."],
    "A Última Casa da Rua": ["Filme psicológico e de terror sobre uma casa assombrada por um passado sombrio.", 
                             "Mistura tragédia com elementos sobrenaturais.", 
                             "Envolvimento com criaturas demoníacas."],
    "O Labirinto do Fauno": ["Filme de terror fantástico dirigido por Guillermo del Toro.", 
                             "Mistura elementos de fábula com horrores da Guerra Civil Espanhola.", 
                             "Filme visualmente deslumbrante com uma narrativa sombria."],
    "O Abismo do Medo": ["Grupo de pessoas fica preso em cavernas subaquáticas, onde algo misterioso começa a caçá-los.", 
                         "Suspense e terror psicológico em um cenário claustrofóbico.", 
                         "Com elementos de sobrevivência e criaturas mutantes."],
    "Cemitério Maldito 2": ["Sequência do filme original, agora com uma nova história envolvendo um novo cemitério.", 
                            "Mistura de terror e drama familiar.", 
                            "Explora a perda e as consequências sobrenaturais."],
    "Dança Macabra": ["Filme de terror sobre uma série de assassinatos e mistérios em uma pequena cidade.", 
                      "Com elementos de mistério e violência.", 
                      "Baseado em um livro de Stephen King."],
    "Teatro Macabro": ["Antologia de contos de terror psicológico e sobrenatural.", 
                       "Filme que mistura drama e horror.", 
                       "Cada história com seu próprio tema de terror."],
    "Ritual de Sangue": ["Terror sobrenatural sobre uma mulher que deve enfrentar uma entidade antiga.", 
                         "Explora rituais ocultos e o medo do desconhecido.", 
                         "Filmado com uma atmosfera tensa e claustrofóbica."],
    "O Dedo Assassino": ["Filme de terror psicológico sobre uma figura ameaçadora que observa suas vítimas.", 
                         "Mistura suspense com o terror do desconhecido.", 
                         "Clássico do cinema de horror psicológico."],
    "O Poço e o Pêndulo": ["Baseado em Edgar Allan Poe, o filme mistura horror gótico e psicológico.", 
                           "Protagonista tenta escapar de torturas medievais.", 
                           "Atmosfera sombria e opressiva."]
}

# Função para escolher um filme aleatório
def get_random_movie():
    return random.choice(list(movies.items()))

# Definindo o estado da aplicação
if 'movie' not in st.session_state:
    st.session_state.movie, st.session_state.tips = get_random_movie()

# Exibindo o título do filme
st.title(f"Filme: {st.session_state.movie}")

# Exibindo as 3 dicas
for i, tip in enumerate(st.session_state.tips):
    st.write(f"Dica {i+1}: {tip}")

# Botão para trocar o filme
if st.button("Trocar Filme"):
    st.session_state.movie, st.session_state.tips = get_random_movie()